export const premiumEvents = [
  {
    id: 1,
    eventName: "Name of Event 1",
    eventImage: "/images/recommendation2.svg",
    eventAddress: "Neharu Stadium, New Delhi",
    eventDate: "24 July, 2024, 9:00 PM - 11:00 PM",
  },
  {
    id: 2,
    eventName: "Name of Event 2",
    eventImage: "/images/recommendation.png",
    eventAddress: "Neharu Stadium, New Delhi",
    eventDate: "24 July, 2024, 9:00 PM - 11:00 PM",
  },
  {
    id: 3,
    eventName: "Name of Event 3",
    eventImage: "/images/recommendation3.svg",
    eventAddress: "Neharu Stadium, New Delhi",
    eventDate: "24 July, 2024, 9:00 PM - 11:00 PM",
  },
  {
    id: 4,
    eventName: "Name of Event 4",
    eventImage: "/images/recommendation4.svg",
    eventAddress: "Neharu Stadium, New Delhi",
    eventDate: "24 July, 2024, 9:00 PM - 11:00 PM",
  },
  {
    id: 5,
    eventName: "Name of Event 5",
    eventImage: "/images/recommendation2.svg",
    eventAddress: "Neharu Stadium, New Delhi",
    eventDate: "24 July, 2024, 9:00 PM - 11:00 PM",
  },
  {
    id: 6,
    eventName: "Name of Event 6",
    eventImage: "/images/recommendation2.svg",
    eventAddress: "Neharu Stadium, New Delhi",
    eventDate: "24 July, 2024, 9:00 PM - 11:00 PM",
  },
  {
    id: 7,
    eventName: "Name of Event 7",
    eventImage: "/images/recommendation.png",
    eventAddress: "Neharu Stadium, New Delhi",
    eventDate: "24 July, 2024, 9:00 PM - 11:00 PM",
  },
  {
    id: 8,
    eventName: "Name of Event 8",
    eventImage: "/images/recommendation3.svg",
    eventAddress: "Neharu Stadium, New Delhi",
    eventDate: "24 July, 2024, 9:00 PM - 11:00 PM",
  },
  {
    id: 9,
    eventName: "Name of Event 9",
    eventImage: "/images/recommendation4.svg",
    eventAddress: "Neharu Stadium, New Delhi",
    eventDate: "24 July, 2024, 9:00 PM - 11:00 PM",
  },
  {
    id: 10,
    eventName: "Name of Event 10",
    eventImage: "/images/recommendation2.svg",
    eventAddress: "Neharu Stadium, New Delhi",
    eventDate: "24 July, 2024, 9:00 PM - 11:00 PM",
  },
];
